"""
Django settings for weatherproj project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env locally only; Azure will use App Settings
load_dotenv(BASE_DIR / ".env")

# ---- Security / Env ----
SECRET_KEY = os.getenv("SECRET_KEY")  # set this in Azure App Settings

DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# Allow Azure host (env var WEBSITE_HOSTNAME is present on App Service)
ALLOWED_HOSTS = [os.getenv("WEBSITE_HOSTNAME", "weather-django-test-app-123.azurewebsites.net")]

# ---- Installed apps ----
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "weather",
]

# ---- Middleware (enable WhiteNoise) ----
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",   # <-- add this
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ---- Templates (yours is fine) ----
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "weatherproj.wsgi.application"

# ---- Database: use writeable path on Azure ----
if os.getenv("WEBSITE_SITE_NAME"):  # running on Azure App Service
    DB_PATH = "/home/site/db.sqlite3"        # persists & writeable
else:
    DB_PATH = BASE_DIR / "db.sqlite3"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(DB_PATH),
    }
}

# ---- i18n (yours is fine) ----

# ---- Static files ----
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"        # required for collectstatic
# Optional: enable gzip/manifest with WhiteNoise
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---- App secrets ----
OPENWEATHER_API_KEY = os.getenv("OPENWEATHER_API_KEY")
