name: Build and deploy Django to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: weather-django-test-app-123   # <-- EXACT App Service name
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ ! -f requirements.txt ]; then echo "requirements.txt missing"; exit 1; fi
          pip install -r requirements.txt

      - name: Collect static (non-fatal if not configured)
        run: |
          if [ -f manage.py ]; then python manage.py collectstatic --noinput || true; fi

      - name: Archive app
        run: |
          mkdir -p build
          zip -r build/app.zip . -x ".git/*" ".github/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/app.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build/app.zip
