# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Django app to Azure Web App - weather-django-test-app-123

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: weather-django-test-app-123   
  PYTHON_VERSION: '3.12'
  WORKING_DIR: '.'                                 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # required for checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django collectstatic
        env:
          DJANGO_SETTINGS_MODULE: weather.settings    
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: "0"
        run: |
          python manage.py collectstatic --noinput

      - name: Create deployment package (zip)
        run: |
          zip -r app.zip . -x "**/.git**" "**/.github**" "**/venv**" "**/__pycache__**"

      - name: Upload artifact for deploy job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: app.zip
          slot-name: Production
